apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dot-prom-29524
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:d50730a9f33d44429303eee2467a3d6ecdc89c3d@sha256:c71bf884fa1e1d312589f47ae766905ecdc3305368e84ef7cc7e38d197325801
          name: container-image
